os:
  - linux
  - osx
  
language: cpp

compiler:
  - gcc
  
before_install:
  
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update ;
      brew install opencv cmake ;      
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update;
    fi

install:

# OpenCV install code (modified from orignal source: https://github.com/jayrambhia/Install-OpenCV)

  # install opencv 3.4
# from https://docs.opencv.org/3.4/d2/de6/tutorial_py_setup_in_ubuntu.html
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
     sudo apt-get install -y cmake
     sudo apt-get install -y gcc g++
     sudo apt-get install -y ffmpeg
     sudo apt-get install -y python-dev python-numpy

     sudo apt-get install -y python3-dev python3-numpy

     sudo apt-get install -y libavcodec-dev libavformat-dev libswscale-dev
     sudo apt-get install -y libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev

     sudo apt-get install -y libgtk2.0-dev

     sudo apt-get install -y libgtk-3-dev
     sudo apt-get install -y libpng-dev
     sudo apt-get install -y libjpeg-dev
     sudo apt-get install -y libopenexr-dev
     sudo apt-get install -y libtiff-dev
     sudo apt-get install -y libwebp-dev
     sudo apt-get install -y libavdevice-dev

     sudo apt-get install -y git
   
     git clone -b '3.4.9' --single-branch --depth 1 https://github.com/opencv/opencv
     cd opencv
     mkdir build
     cd build
     cmake -D BUILD_EXAMPLES=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF ..
     make -j4
     sudo make install
     cd ..
     cd .. 
     fi
  
before_script:
  - cd build
  - cmake ..

script: 
  - make OCVWarp.bin
  - make getfourcc.bin 
   
deploy:
  provider: releases
  token: $mytokenname
  file_glob: true
  file: OCVWarp*
  draft: true
  #on:
  #  tags: true
  edge: true
