os:
  
  - osx
  
language: cpp

compiler:
  - gcc
  
before_install:  
  - brew update ;
  
install:
 - brew install opencv cmake;
 
before_script:
  - cd build
  - cmake ..

script: 
  - make OCVWarp.bin
  - make getfourcc.bin 
   
deploy:
  provider: releases
  token: $mytokenname
  file_glob: true
  file: OCVWarp*
  draft: true
  #on:
  #  tags: true
  edge: true
