language: cpp

compiler:
  - gcc
  
before_install:
  - sudo add-apt-repository -y ppa:timsc/opencv-3.3
  - sudo apt-get update

install:

# OpenCV install code (modified from orignal source: https://github.com/jayrambhia/Install-OpenCV)

  # install opencv 3.4
# from https://docs.opencv.org/3.4/d2/de6/tutorial_py_setup_in_ubuntu.html
   - sudo apt-get install -y cmake
   - sudo apt-get install -y gcc g++
   - sudo apt-get install -y ffmpeg
   - sudo apt-get install -y python-dev python-numpy

   - sudo apt-get install -y python3-dev python3-numpy

   - sudo apt-get install -y libavcodec-dev libavformat-dev libswscale-dev
   - sudo apt-get install -y libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev

   - sudo apt-get install -y libgtk2.0-dev

   - sudo apt-get install -y libgtk-3-dev
   - sudo apt-get install -y libpng-dev
   - sudo apt-get install -y libjpeg-dev
   - sudo apt-get install -y libopenexr-dev
   - sudo apt-get install -y libtiff-dev
   - sudo apt-get install -y libwebp-dev
   - sudo apt-get install -y libavdevice-dev

   - sudo apt-get install -y git
   
   - git clone -b 3.4 https://github.com/opencv/opencv
   - cd opencv
   - mkdir build
   - cd build
   - cmake ..
   - make -j4
   - sudo make install
  
before_script:
  - cd build
  - cmake ..

script: 
  - make OCVWarp.bin
  # modified from https://github.com/lupoDharkael/smilla-enlarger/pull/2/files
  - mkdir -p appdir/usr/bin ; strip OCVWarp.bin ; cp OCVWarp.bin ./appdir/usr/bin/
  - mkdir -p appdir/usr/share/applications ; cp ../appdir/OCVWarp.desktop ./appdir/usr/share/applications/
  - mkdir -p appdir/usr/share/icons/hicolor/256x256/apps ; cp ../appdir/OCVWarp.png ./appdir/usr/share/icons/hicolor/256x256/apps/
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - export VERSION=$(git rev-parse --short HEAD) # linuxdeployqt uses this for naming the file
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage

after_success:
  - find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - curl --upload-file OCVWarp*.AppImage https://transfer.sh/OCVWarp1.20-x86_64.AppImage
