version: 1.0.{build}
# base image
image: Visual Studio 2015


configuration: Release

platform: x64

install:
- choco install opencv --version=3.4.3
- cmd: setx -m OPENCV_DIR C:\tools\OpenCV\Build\x64\vc14
- refreshenv

build:
  project: OCVWarpNorth.vcxproj
  project: OCVWarp.vcxproj

  verbosity: minimal
 
artifacts:

- path: x64\Release\OCVWarpNorth.exe
- path: x64\Release\OCVWarp.exe


