version: 2.50.{build}
# base image
image: Visual Studio 2013

platform: Win32
configuration: Release       

install:
 - ps: Start-FileDownload https://github.com/opencv/opencv/archive/3.4.9.zip
 - 7z x 3.4.9.zip
 - cd opencv-3.4.9
 - cd modules\videoio\src
 - ps: Start-FileDownload https://github.com/hn-88/opencvpatch/raw/master/cap_dshow.cpp
 
 - cd ..\..\..
 - md build
 - cd build
 - cmake -D BUILD_EXAMPLES=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -G "Visual Studio 12 2013" -A Win32 ..
 - cmake --build .  --config release
 - cd ..
 - cd .. 
 - SET "OpenCV_DIR=C:\projects\ocvwarp\opencv-3.4.9\build\install"
  
  
build:
  project: OCVWarpWin32.vcxproj

  verbosity: minimal
 
artifacts:
- path: Win32\Release\OCVWarp.exe

