version: 2.50.{build}
# base image
image: Visual Studio 2015

platform: Win32
configuration: Release       

install:
 - ps: Start-FileDownload https://github.com/opencv/opencv/archive/3.4.9.zip
 - 7z x 3.4.9.zip
 - cd opencv-3.4.9
 - cd modules\videoio\src
 - ps: Start-FileDownload https://github.com/hn-88/opencvpatch/raw/master/cap_dshow.cpp
 
 - cd ..\..\..
 - md build
 - cd build
 - cmake -D BUILD_EXAMPLES=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_opencv_world=ON -G "Visual Studio 14 2015" -A Win32 ..
 - cmake --build .  --config release
 - cmake --build .  --target install --config release
 - cd ..
 - cd .. 
 - cmd: setx -m OpenCV_DIR C:\projects\ocvwarp\opencv-3.4.9\build\install\x86\vc14
 - cmd: setx path "%path%;C:\projects\ocvwarp\opencv-3.4.9\build\install\x86\vc14\bin;C:\projects\ocvwarp\opencv-3.4.9\build\install\x86\vc14\lib"
 - refreshenv
  
  
build_script:
  # - copy CMakeListsWin32.txt CMakeLists.txt
  - copy C:\projects\ocvwarp\opencv-3.4.9\build\install\x86\vc14\bin\*.dll . 
  - copy C:\projects\ocvwarp\opencv-3.4.9\build\install\x86\vc14\lib\*.lib . 
  - cd build
  - cmake -G "Visual Studio 14 2015" -A Win32 ..
  - cmake --build . --target OCVWarp.bin
  

artifacts:
  - path: build\OCVWarp.bin.exe
    name: OCVWarp.exe

  - path: build\*.dll
    name: OpenCV dlls
    
 
