version: 2.11.1.{build}

image: Visual Studio 2015
configuration: Release
platform: Win32

environment:
  QTDIR: C:\Qt\5.11\mingw53_32

install:
  - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin
  - set CC=C:\Qt\Tools\mingw530_32\bin\gcc.exe
  - set CXX=C:\Qt\Tools\mingw530_32\bin\g++.exe
  - set Qt5_DIR=%QTDIR%\lib\cmake\Qt5
  - set PATH=%PATH:C:\Program Files\Git\usr\bin=% # trick to remove sh.exe
  
  - ps: Start-FileDownload https://github.com/opencv/opencv/archive/3.4.9.zip
  - 7z x 3.4.9.zip
  - cd opencv-3.4.9
  - cd modules\videoio\src
  - ps: Start-FileDownload https://github.com/hn-88/opencvpatch/raw/master/cap_dshow.cpp
  
  - cd ..\..\..
  - md build
  - cd build
  - cmake -D BUILD_EXAMPLES=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -G "MinGW Makefiles" ..
  - mingw32-make -j2
  - mingw32-make install
  - cd ..
  - cd .. 
  - SET "OpenCV_DIR=C:\projects\ocvwarp\opencv-3.4.9\build\install"
   
build_script:
  - cd build
  - copy C:\Qt\Tools\mingw530_32\bin\*.dll .
  - cmake -G "MinGW Makefiles" ..
  - mingw32-make OCVWarp.bin
  - echo "ldd to find dependencies " 
  - ldd OCVWarp.bin.exe

artifacts:
  - path: build\OCVWarp.bin.exe
    name: OCVWarp.exe

  - path: opencv-3.4.9\build\install\x64\mingw\bin\*.dll
    name: OpenCV dlls
    
  - path: build\*.dll
    name: Runtime dlls
