version: 2.11.1.{build}

image: Visual Studio 2015
configuration: Release
platform: Win32

environment:
  QTDIR: C:\Qt\5.11\mingw53_32

install:
  - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin
  - set CC=C:\Qt\Tools\mingw530_32\bin\gcc.exe
  - set CXX=C:\Qt\Tools\mingw530_32\bin\g++.exe
  - set Qt5_DIR=%QTDIR%\lib\cmake\Qt5
  - set PATH=%PATH:C:\Program Files\Git\usr\bin=% # trick to remove sh.exe
  
  - ps: Start-FileDownload https://github.com/opencv/opencv/archive/3.4.9.zip
  - 7z x 3.4.9.zip
  - cd opencv-3.4.9
  - md build
  - cd build
  - cmake -D BUILD_EXAMPLES=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -G "MinGW Makefiles" ..
  - make -j4
  - cd ..
  - cd .. 
  - SET "OpenCV_DIR=C:\opencv3.4.9\build\install"
   
build_script:
  - cd build
  - cmake ..
  - make OCVWarp.bin
