version: 1.0.{build}
# base image
image: Visual Studio 2015

matrix:
    - platform: x86
       
    - platform: x64
       
configuration: Release


install:
- choco install opencv --version=3.4.3

- cmd: appveyorsetdir.bat

  
build:
  project: OCVWarp.vcxproj

  verbosity: minimal
 
artifacts:
- path: x64\Release\OCVWarp.exe


