version: 2.50.{build}
# base image
image: Visual Studio 2015

platform: Win32
configuration: Release       

install:
 - ps: Start-FileDownload https://github.com/opencv/opencv/archive/3.4.9.zip
 - 7z x 3.4.9.zip
 - cd opencv-3.4.9
 - cd modules\videoio\src
 - ps: Start-FileDownload https://github.com/hn-88/opencvpatch/raw/master/cap_dshow.cpp
 
 - cd ..\..\..
 - md build
 - cd build
 - cmake -D BUILD_EXAMPLES=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -G "Visual Studio 14 2015" -A Win32 ..
 - cmake --build .  --config release
 - cmake --build .  --target install --config release
 - cd ..
 - cd .. 
 - cmd: setx -m OPENCV_DIR C:\projects\ocvwarp\opencv-3.4.9\build\install
 - refreshenv
  
  
build_script:
  - cd build
  - cmake -G "Visual Studio 14 2015" -A Win32 ..
  - cmake --build . --target OCVWarp.bin
  

artifacts:
  - path: build\OCVWarp.bin.exe
    name: OCVWarp.exe

  - path: opencv-3.4.9\build\install\*\*\bin\*.dll
    name: OpenCV dlls
    
 
